services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - '3000:3000'
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - dashboard_data_dev:/app/data
    environment:
      - NODE_ENV=development
    restart: unless-stopped

volumes:
  dashboard_data_dev:
    driver: local
